# Generated by Django 3.2 on 2022-04-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stipe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
