# Generated by Django 3.2 on 2022-04-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220410_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stipe_pid',
            new_name='stripe_pid',
        ),
    ]
